// Mocks generated by Mockito 5.4.6 from annotations
// in ayni/test/profile/presentation/blocs/profile_bloc_test_new.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:ayni/core/utils/api_response.dart' as _i2;
import 'package:ayni/profile/data/models/profile_models.dart' as _i6;
import 'package:ayni/profile/domain/entities/profile.dart' as _i5;
import 'package:ayni/profile/presentation/viewmodels/profile_viewmodel.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiResponse_0<T> extends _i1.SmartFake
    implements _i2.ApiResponse<T> {
  _FakeApiResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileViewModel extends _i1.Mock implements _i3.ProfileViewModel {
  MockProfileViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResponse<_i5.Profile>> getProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, [userId]),
            returnValue: _i4.Future<_i2.ApiResponse<_i5.Profile>>.value(
              _FakeApiResponse_0<_i5.Profile>(
                this,
                Invocation.method(#getProfile, [userId]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<_i5.Profile>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.Profile>> getCurrentProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentProfile, []),
            returnValue: _i4.Future<_i2.ApiResponse<_i5.Profile>>.value(
              _FakeApiResponse_0<_i5.Profile>(
                this,
                Invocation.method(#getCurrentProfile, []),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<_i5.Profile>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.Profile>> createProfile(
    _i6.CreateProfileRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createProfile, [request]),
            returnValue: _i4.Future<_i2.ApiResponse<_i5.Profile>>.value(
              _FakeApiResponse_0<_i5.Profile>(
                this,
                Invocation.method(#createProfile, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<_i5.Profile>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.Profile>> updateProfile(
    String? profileId,
    _i6.UpdateProfileRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [profileId, request]),
            returnValue: _i4.Future<_i2.ApiResponse<_i5.Profile>>.value(
              _FakeApiResponse_0<_i5.Profile>(
                this,
                Invocation.method(#updateProfile, [profileId, request]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<_i5.Profile>>);

  @override
  _i4.Future<_i2.ApiResponse<void>> deleteProfile(String? profileId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProfile, [profileId]),
            returnValue: _i4.Future<_i2.ApiResponse<void>>.value(
              _FakeApiResponse_0<void>(
                this,
                Invocation.method(#deleteProfile, [profileId]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<void>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.Profile>> uploadProfilePicture(
    String? profileId,
    String? imagePath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfilePicture, [profileId, imagePath]),
            returnValue: _i4.Future<_i2.ApiResponse<_i5.Profile>>.value(
              _FakeApiResponse_0<_i5.Profile>(
                this,
                Invocation.method(#uploadProfilePicture, [
                  profileId,
                  imagePath,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<_i5.Profile>>);

  @override
  _i4.Future<_i2.ApiResponse<List<_i5.Profile>>> searchProfiles({
    String? search,
    String? location,
    List<String>? interests,
    int? page = 1,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchProfiles, [], {
              #search: search,
              #location: location,
              #interests: interests,
              #page: page,
              #limit: limit,
            }),
            returnValue: _i4.Future<_i2.ApiResponse<List<_i5.Profile>>>.value(
              _FakeApiResponse_0<List<_i5.Profile>>(
                this,
                Invocation.method(#searchProfiles, [], {
                  #search: search,
                  #location: location,
                  #interests: interests,
                  #page: page,
                  #limit: limit,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<List<_i5.Profile>>>);

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );

  @override
  bool validateProfileData({
    String? firstName,
    String? lastName,
    String? email,
    String? phoneNumber,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#validateProfileData, [], {
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
              #phoneNumber: phoneNumber,
            }),
            returnValue: false,
          )
          as bool);

  @override
  String getDisplayName(_i5.Profile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#getDisplayName, [profile]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#getDisplayName, [profile]),
            ),
          )
          as String);

  @override
  bool isProfileComplete(_i5.Profile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#isProfileComplete, [profile]),
            returnValue: false,
          )
          as bool);

  @override
  double getProfileCompletionPercentage(_i5.Profile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#getProfileCompletionPercentage, [profile]),
            returnValue: 0.0,
          )
          as double);
}
