// Mocks generated by Mockito 5.4.6 from annotations
// in ayni/test/profile/data/repositories/profile_repository_test_new.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:ayni/core/services/storage_service.dart' as _i6;
import 'package:ayni/core/utils/api_response.dart' as _i2;
import 'package:ayni/profile/data/datasources/profile_data_source.dart' as _i3;
import 'package:ayni/profile/data/models/profile_models.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiResponse_0<T> extends _i1.SmartFake
    implements _i2.ApiResponse<T> {
  _FakeApiResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileDataSource extends _i1.Mock implements _i3.ProfileDataSource {
  MockProfileDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResponse<_i5.ProfileModel>> getProfileById(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProfileById, [userId]),
            returnValue: _i4.Future<_i2.ApiResponse<_i5.ProfileModel>>.value(
              _FakeApiResponse_0<_i5.ProfileModel>(
                this,
                Invocation.method(#getProfileById, [userId]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<_i5.ProfileModel>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.ProfileModel>> getCurrentProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentProfile, []),
            returnValue: _i4.Future<_i2.ApiResponse<_i5.ProfileModel>>.value(
              _FakeApiResponse_0<_i5.ProfileModel>(
                this,
                Invocation.method(#getCurrentProfile, []),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<_i5.ProfileModel>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.ProfileModel>> createProfile(
    _i5.CreateProfileRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createProfile, [request]),
            returnValue: _i4.Future<_i2.ApiResponse<_i5.ProfileModel>>.value(
              _FakeApiResponse_0<_i5.ProfileModel>(
                this,
                Invocation.method(#createProfile, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<_i5.ProfileModel>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.ProfileModel>> updateProfile(
    String? profileId,
    _i5.UpdateProfileRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [profileId, request]),
            returnValue: _i4.Future<_i2.ApiResponse<_i5.ProfileModel>>.value(
              _FakeApiResponse_0<_i5.ProfileModel>(
                this,
                Invocation.method(#updateProfile, [profileId, request]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<_i5.ProfileModel>>);

  @override
  _i4.Future<_i2.ApiResponse<void>> deleteProfile(String? profileId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProfile, [profileId]),
            returnValue: _i4.Future<_i2.ApiResponse<void>>.value(
              _FakeApiResponse_0<void>(
                this,
                Invocation.method(#deleteProfile, [profileId]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<void>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.ProfileModel>> uploadProfilePicture(
    String? profileId,
    String? imagePath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfilePicture, [profileId, imagePath]),
            returnValue: _i4.Future<_i2.ApiResponse<_i5.ProfileModel>>.value(
              _FakeApiResponse_0<_i5.ProfileModel>(
                this,
                Invocation.method(#uploadProfilePicture, [
                  profileId,
                  imagePath,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<_i5.ProfileModel>>);

  @override
  _i4.Future<_i2.ApiResponse<List<_i5.ProfileModel>>> searchProfiles({
    String? search,
    String? location,
    List<String>? interests,
    int? page = 1,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchProfiles, [], {
              #search: search,
              #location: location,
              #interests: interests,
              #page: page,
              #limit: limit,
            }),
            returnValue:
                _i4.Future<_i2.ApiResponse<List<_i5.ProfileModel>>>.value(
                  _FakeApiResponse_0<List<_i5.ProfileModel>>(
                    this,
                    Invocation.method(#searchProfiles, [], {
                      #search: search,
                      #location: location,
                      #interests: interests,
                      #page: page,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponse<List<_i5.ProfileModel>>>);

  @override
  List<_i5.ProfileModel> getCachedProfiles() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProfiles, []),
            returnValue: <_i5.ProfileModel>[],
          )
          as List<_i5.ProfileModel>);

  @override
  void cacheProfiles(List<_i5.ProfileModel>? profiles) => super.noSuchMethod(
    Invocation.method(#cacheProfiles, [profiles]),
    returnValueForMissingStub: null,
  );

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.ProfileModel? getCachedProfileById(String? profileId) =>
      (super.noSuchMethod(Invocation.method(#getCachedProfileById, [profileId]))
          as _i5.ProfileModel?);

  @override
  void cacheProfile(_i5.ProfileModel? profile) => super.noSuchMethod(
    Invocation.method(#cacheProfile, [profile]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i6.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveUserData(String? userData) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserData, [userData]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(Invocation.method(#getBool, [key])) as bool?);

  @override
  _i4.Future<void> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(Invocation.method(#getString, [key])) as String?);

  @override
  _i4.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearAuthData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAuthData, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
